# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  #use_frameworks!

pod 'SDWebImage', '~>3.8'
#pod 'ReachabilitySwift', '~> 2.4'

  # Pods for iOSTest
  

end
